"""Add excerpt to Story model

Revision ID: 276f61324fb1
Revises: d23d6e45e5f1
Create Date: 2024-09-29 20:41:44.189059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '276f61324fb1'
down_revision = 'd23d6e45e5f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('story', schema=None) as batch_op:
        batch_op.add_column(sa.Column('excerpt', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('story', schema=None) as batch_op:
        batch_op.drop_column('excerpt')

    # ### end Alembic commands ###
